dispatch updates

diff --git a/dispatch b/dispatch
--- a/dispatch
+++ b/dispatch
@@ -67,24 +67,29 @@ system ()
 
 power ()
 {
+    mode=
     case $1 in
         auto)
             # based on AC connection status
             [[ $(cat /sys/class/power_supply/AC/online) > 0 ]] \
-            && power max || power min; return ;;
+            && power max || power min; return || echo "FAILED HERE TOO"
+            ;;
         toggle)
             _mode=(min max); _state=$(cat $STATEROOT/power)
             [[ $_state == "${_mode[0]}" ]] && power ${_mode[1]} && return
-            power ${_mode[0]}; return
+            power ${_mode[0]}; return || echo "FAILED"
             ;;
         cycle)
-            _mode=(min med max mov); _state=$(cat $STATEROOT/power)
-            for _s in $(seq 0 $((${#_mode[@]} - 1)))
-            do echo $_s; [[ ${_state:-} == ${_mode[$_s]} ]] \
-            && power ${_mode[$(( ++_s % ${#_mode[@]} ))]} && return; done
-            power auto; return
+            _mode=(min max mov); _state=$(cat $STATEROOT/power); _post="power auto"
+            for _s in $(seq 0 $((${#_mode[@]} - 1))); do 
+                if [[ ${_state:-} == ${_mode[$_s]} ]]; then
+                    _post=; power ${_mode[$(( ++_s % ${#_mode[@]} ))]} && break;
+                fi
+            done
+	    eval "$_post"; exit
             ;;
         min)
+            mode=min
             nmi_watchdog=false
             cpu_powersave=true
             display_powersave=true
@@ -99,6 +104,7 @@ power ()
             backlight_percent=75
             ;;
         med)
+            mode=med
             cpu_powersave=true
             display_powersave=true
             powersave_bus=true
@@ -113,6 +119,7 @@ power ()
             backlight_percent=75
             ;;
         max)
+            mode=max
             nmi_watchdog=true
             cpu_powersave=false
             display_powersave=false
@@ -127,6 +134,7 @@ power ()
             backlight_percent=100
             ;;
         mov)
+            mode=mov
             nmi_watchdog=true
             cpu_powersave=false
             display_powersave=false
@@ -144,10 +152,6 @@ power ()
     esac
 
     # c.f. https://lesswatts.org/tips
-
-    # DISPLAY ---------------------------------------------------------
-
-    mode=$1 # e.g. min, max
 
     # DISPLAY ---------------------------------------------------------
 
@@ -175,9 +179,15 @@ power ()
     # BUS -------------------------------------------------------------
     $powersave_bus && _bus=auto || _bus=on
     $powersave_wacom && _wacom=auto || _wacom=on
-    for _path in /sys/bus/*/devices/*; do
-       _pwr=$_bus; [[ -f "$_path/manufacturer" && "$(cat "$_path/manufacturer")" == "Tablet" ]] && _pwr=$_wacom
-       [[ -f "$_path/power/control" ]] && sudo echo -n $_pwr > "$_path/power/control"
+    #not sure about the other buses, so just going for pci/usb
+    #for _path in /sys/bus/*/devices/*/power/control; do
+    for _path in /sys/bus/{pci,usb}/devices/*/power/control; do
+        sudo echo -n $_bus > "$_path" || true;
+    done
+    for _path in /sys/bus/usb/devices/*/manufacturer; do
+        if [[ -f "$_path" && "$(cat "$_path")" == "Tablet" ]]; then
+            sudo echo -n $_wacom > "$(dirname $_path)/power/control" || true;
+        fi
     done
 
     # CPU -------------------------------------------------------------
@@ -237,9 +247,10 @@ power ()
     $nmi_watchdog && _nmi=1 || _nmi=0; sudo sysctl -q kernel.nmi_watchdog=$_nmi
 
     # RECORD STATE ----------------------------------------------------
-    sudo echo -n $1 > $STATEROOT/power
+    sudo echo -n $mode > $STATEROOT/power
+    sudo chmod a+w $STATEROOT/power
 
-    Notify "$1 power mode"
+    #Notify "$1 power mode"
 
 }
 
@@ -374,9 +385,11 @@ _Log () { logger "SYSTEM ACTION: $* (${FUNCNAME[1]})"; }
 
 if [[ -n $ROOTMODE ]]
 then
-    Notify () { logger "$*"; su ${USER:-} -c "notify-send \"$*\""; }
+    # Notify () { logger "$*"; su ${USER:-} -c "notify-send \"$*\""; }
+    :
 else
-    Notify () { logger "$*"; notify-send "$*"; }
+    # Notify () { logger "$*"; notify-send "$*"; }
+    :
 fi
 
 _Is_True () {
